### ISSUE TITLE
changes in package.json

### ISSUE THREAD

**Issue by DarshitJain04** [devlup-labs/auto-submit-quiz#10]
Change the `description` and `url` property in `package.json` file

**Comment by github4maninder** [comment]
hi, I would like to work on this. I can update the url to : "https://github.com/devlup-labs/auto-submit-quiz"

for the description I would like to suggest as : "Auto-Submit-Quiz application built with React".
any suggestions regarding the description are most welcome.

**Comment by DarshitJain04** [comment]
> hi, I would like to work on this. I can update the url to : "https://github.com/devlup-labs/auto-submit-quiz"
> 
> for the description I would like to suggest as : "Auto-Submit-Quiz application built with React". any suggestions regarding the description are most welcome.

Hey @github4maninder ! Sure, go ahead!
The description can be something like: _Google forms auto-submit application built with React JS_

**Comment by github4maninder** [comment]
thanks for your response. I have created a PR.
